[build-system]
requires = ["hatchling>=1.5", "hatch-nodejs-version"]
build-backend = "hatchling.build"

[project]
name = "nbapi"
dynamic = ["version"]
description = "Turn Jupyter Notebooks in to APIs"